# DiffSeg UNet Project Configuration
# Edit these values to control training and inference without code changes

# Dataset paths
inpainted_dir: "C:/Users/raghu/OneDrive/Desktop/Frick_diffseg/inpainted_images"
masks_dir: "C:/Users/raghu/OneDrive/Desktop/Frick_diffseg/masks"

# DataLoader
batch_size: 16
num_workers: 2
pin_memory: true

# Image/Mask size
resize_height: 512
resize_width: 512

# Validation split
val_split: 0.2

# Model
model:
  name: "unet"
  weights: true

# Training
epochs: 10
learning_rate: 1e-4
optimizer: "adam"
loss: "bce_dice"

# Inference
inference_output_dir: "./outputs"

# Device
use_cuda: true